//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub status: String,
    pub priority: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub due_date: Option<Date>,
    pub completed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::task_tags::Entity")]
    TaskTags,
}

impl Related<super::task_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskTags.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::task_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::task_tags::Relation::Tasks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
